const cacheName = 'GAMEDEV-v1';

self.addEventListener("install", (event) => {
    console.log("[Service Worker] Install");
    event.waitUntil(
        (async () => {
            const cache = await caches.open(cacheName);
            console.log("[Service Worker] Caching everything");
            try {
                await cache.addAll(filesList);
            } catch (error) {
                console.error(`[Service Worker] ${error}`);
                for (let f of filesList) {
                    try {
                        //console.log(`[Service Worker] Caching ${f}`);
                        await cache.add(f);
                    } catch (error) {
                        console.error(`[Service Worker] ${error}:`, f);
                    }
                }
            }
        })(),
    );
});

self.addEventListener("activate", (e) => {
    e.waitUntil(
        caches.keys().then((keyList) => {
            return Promise.all(
                keyList.map((key) => {
                    if (key === cacheName) {
                        return;
                    }
                    console.warn(`[Service Worker] Cache removed: ${key}`);
                    return caches.delete(key);
                }),
            );
        }),
    );
});

self.addEventListener("fetch", (event) => {
    event.respondWith(
        (async () => {
            const cachedResponse = await caches.match(event.request,{ignoreMethod:true});
            if (cachedResponse) {
                console.log(`[Service Worker] Fetching resource: ${event.request.url}`);
                return cachedResponse;
            }
            try {
                const networkResponse = await fetch(event.request);
                if (networkResponse.ok) {
                    const cache = await caches.open(cacheName);
                    console.log(`[Service Worker] Caching new resource: ${event.request.url}`);
                    cache.put(event.request, networkResponse.clone());
                }
                return networkResponse;
            } catch (error) {
                console.error(`[Service Worker] ${error}`, event.request.url);
                return Response.error();
            }
        })(),
    );
});

export const filesList = [
    "game_jams/[igmc_2017]_gamedev_the_beginning/",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Battle.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Battle.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Dream.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Dream.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Happy.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Happy.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Sewers.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Sewers.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Title.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgm/Title.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Dripping.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Dripping.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Forest.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Forest.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/HouseNight.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/HouseNight.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Night.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/bgs/Night.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Attack1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Attack1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Attack2.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Attack2.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/BattleStart.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/BattleStart.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Buzzer1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Buzzer1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Buzzer2.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Buzzer2.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Cancel.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Cancel.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/CandleOff.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/CandleOff.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/CandleOn.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/CandleOn.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse2.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse2.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse3.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Collapse3.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Cursor.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Cursor.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Damage1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Damage1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Equip.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Equip.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Escape.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Escape.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Evasion1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Evasion1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/FirstAid.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/FirstAid.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Load.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Load.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MagicReflection.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MagicReflection.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Miss.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Miss.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MonsterStep1.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MonsterStep1.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MonsterStep2.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MonsterStep2.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MouseKeyboard.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/MouseKeyboard.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/OK.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/OK.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Recovery.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Recovery.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Save.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Save.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Slash.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Slash.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/SmbMushroom.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/SmbMushroom.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/SmbPotion.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/SmbPotion.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/StupidIdeas.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/StupidIdeas.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Trick.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Trick.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Use.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/Use.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/WalkGrass.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/WalkGrass.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/WallHit.m4a",
    "game_jams/[igmc_2017]_gamedev_the_beginning/audio/se/WallHit.ogg",
    "game_jams/[igmc_2017]_gamedev_the_beginning/CreateListFiles4Cache.sh",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Actors.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Animations.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Armors.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/BattleHUD.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Classes.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/CommonEvents.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Enemies.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Items.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map001.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map003.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map004.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map005.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map006.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map007.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map008.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Map009.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/MapHUD.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/MapInfos.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Skills.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/States.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/System.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Tilesets.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Troops.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/data/Weapons.json",
    "game_jams/[igmc_2017]_gamedev_the_beginning/fonts/gamefont.css",
    "game_jams/[igmc_2017]_gamedev_the_beginning/fonts/manaspc.ttf",
    "game_jams/[igmc_2017]_gamedev_the_beginning/icon/icon-192.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/icon/icon-512.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/icon/icon.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/animations/FirstAid.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/animations/Hit.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/animations/Slash.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/animations/StupidIdeas.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/animations/Trick.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/battlebacks1/Battleback0.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/battlebacks1/BattlebackForest.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/battlebacks1/BattlebackSewers.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/battlebacks1/BattlebackTest.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Cauldron.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Dalfgan.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/$FatherOnSofa.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Floppy.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/$JoeBlinking.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$JoeOnChairDressed.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$JoeOnChair.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$JoeOnFloor.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/$JoeOnSofa.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$JoeSleeping.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$LED.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/$MotherShocked.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Ninjato.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/$!PCScreen.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Pizza.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$SmbMushroomGlow.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/!$Window.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/Characters.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/Monsters.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/characters/Vehicle.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/faces/Faces.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/parallaxes/Sky_1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/parallaxes/Sky_2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/parallaxes/Sky_3.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/parallaxes/Sky_4.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/15MinutesLater.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Chapter1Lets.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Chapter1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ControlsMobile0.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ControlsMobile1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Controls.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Darkness.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/GameOver.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/GiantMushroomManShadow.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/JustKidding.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Light.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/LightVito.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/Prologue.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarCandleOff.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarCandleOn0.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarCandleOn1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarCandleOn.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarEquipment.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarInventoryHot.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarInventory.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/QuickbarSkills.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued3.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued4.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued5.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued6.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued7.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/ToBeContinued8.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/pictures/WindowLightOverlay.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_black.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_blue.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_gray.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_green.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_orange.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_pink.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_red.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_white.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sfonts/manaspc_yellow.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/SumRndmDde/gameover/EmptyBlack.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_actors/Joe.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_actors/Vito.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/Father.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/FatherSleep.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/GiantMushroomMan.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/GiantMushroomManSleep.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/Mother.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/MotherSleep.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/MushroomMan.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/MushroomManSleep.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/SlimeBlue.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/SlimeGreen.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/sv_enemies/SlimeRed.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Balloon.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/BubbleArrowBlack.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/BubbleArrowWhite.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/ButtonSet.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Damage.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Destination2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Destination.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/EnemyHP_A.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/EnemyHP_B.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/GameOver.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/IconSet.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/JoeSleeping.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/LED.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Loading.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Shadow1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Shadow2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/StartImage.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/States.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/TurnIndicator.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/VNButtons.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Weapons1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Weapons2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Weapons3.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/WindowLightOverlay.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/Window.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/WindowStars.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/system/WindowWhite.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Forest_A2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Forest_B.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Room_A2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Room_A4.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Room_B.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Sewers_A1.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Sewers_A2_2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Sewers_A2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Sewers_A4_2.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/tilesets/Sewers_A4.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/titles1/Title.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/ButtonCancelHot.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/ButtonCancel.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/ButtonOkHot.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/ButtonOk.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/DPadHot.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/VirtualButtons/DPad.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/weather/Firefly.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/img/weather/Leaf.png",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/fpsmeter.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/iphone-inline-video.browser.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/lz-string.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/pixi.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/pixi-picture.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/libs/pixi-tilemap.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/main.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_ALOE_VirtualButtons_Addon.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/ALOE_VirtualButtons.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_Battle_Scene_Remake.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/Community_Basic.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_CustomizeOptions.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/CXJ_Exit.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/DestinationSprite.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/FullscreenOptions.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/GALV_CustomTitle.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/GALV_DiagonalMovement.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/GALV_MessageStyles.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/GALV_VisualNovelChoices.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_HideInactiveCursor.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_Mixed_Edits_To_Core_Files.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/MOG_ActorTurnIndicator.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/MOG_Weather_EX.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/MrTS_NoItemCategories.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_NoAccidentalDialogSkip.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_SavefileList_Remake.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_SetRenderer.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_SimpleNameInput.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_SimpleSkills.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_SingleClickCommands.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/SRD_ActorSelect.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/SRD_AudioFader.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/SRD_BattleStatusCustomizer.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/SRD_BattleStatusCustomizer_Part2.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/SRD_GameOverCore.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_StatusWindow_Remake.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_TurnSwitchesOnStart.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/TYR_FollowerControl.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/VE_BasicModule.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/VE_SFont.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_WASD_Controls+.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_BattleEngineCore.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/_YEP_EquipCore_Edits.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_EquipCore.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_FpsSynchOption.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_MainMenuManager.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_MessageCore.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_PictureCommonEvents.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_RegionRestrictions.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YEP_X_VisualHpGauge.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins/YSP_Preloader.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/plugins.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_core.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_managers.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_objects.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_scenes.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_sprites.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/js/rpg_windows.js",
    "game_jams/[igmc_2017]_gamedev_the_beginning/movies/Door1.mp4",
    "game_jams/[igmc_2017]_gamedev_the_beginning/movies/Door1.webm",
    "game_jams/[igmc_2017]_gamedev_the_beginning/screenshots/screenshot_00.webp",
    "game_jams/[igmc_2017]_gamedev_the_beginning/screenshots/screenshot_01.webp"
]
